let editingId=null,uploaded=[];
const $=s=>document.querySelector(s);const show=(id)=>{document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.side-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id))};
document.addEventListener('DOMContentLoaded',async()=>{if(!configured){$('#setup-note').classList.remove('hidden');$('#login-view').classList.add('hidden');$('#admin-app').classList.remove('hidden');show('#properties-view');await renderList();}else{const {data}=await supabaseClient.auth.getSession();if(data.session)enter();}$('#login-form').onsubmit=login;$('#property-form').onsubmit=saveProperty;$('#images').onchange=preview;document.querySelectorAll('.side-nav button').forEach(b=>b.onclick=()=>{show(b.dataset.view);if(b.dataset.view==='#properties-view')renderList();if(b.dataset.view==='#form-view'&&!editingId)resetForm()});$('#logout').onclick=async()=>{if(supabaseClient)await supabaseClient.auth.signOut();location.reload()};});
async function login(e){e.preventDefault();$('#login-msg').textContent='Entrando...';const {error}=await supabaseClient.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error){$('#login-msg').textContent=error.message;return}enter()}
async function enter(){$('#login-view').classList.add('hidden');$('#admin-app').classList.remove('hidden');show('#properties-view');await renderList()}
function resetForm(){editingId=null;uploaded=[];$('#property-form').reset();$('#form-title').textContent='Novo imóvel';$('#published').checked=true;$('#status').value='Disponível';$('#image-previews').innerHTML=''}
function preview(e){uploaded=[...e.target.files];$('#image-previews').innerHTML=uploaded.map(f=>`<img src="${URL.createObjectURL(f)}">`).join('')}
async function renderList(){const list=await getProperties(true);$('#admin-list').innerHTML=list.map(p=>`<div class="admin-item"><img src="${p.images?.[0]||'assets/una/una-1.jpg'}"><div><strong>${p.title}</strong><div class="location">${p.neighborhood||''} · ${money(p.price)} · ${p.published===false?'Oculto':'Publicado'}</div></div><div class="admin-actions">${p.id!=='una-areiao'?`<button class="btn btn-light" onclick="editProperty('${p.id}')">Editar</button><button class="btn btn-danger" onclick="deleteProperty('${p.id}')">Excluir</button>`:'<span class="pill">Imóvel inicial</span>'}</div></div>`).join('')}
async function uploadImages(id,files){if(!supabaseClient)return await filesToData(files);const urls=[];for(const f of files){const ext=f.name.split('.').pop();const path=`${id}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await supabaseClient.storage.from('property-images').upload(path,f,{upsert:false});if(error)throw error;const {data}=supabaseClient.storage.from('property-images').getPublicUrl(path);urls.push(data.publicUrl)}return urls}
function filesToData(files){return Promise.all(files.map(f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})))}
async function saveProperty(e){e.preventDefault();const btn=$('#save-btn');btn.disabled=true;btn.textContent='Salvando...';try{const id=editingId||crypto.randomUUID();let images=uploaded.length?await uploadImages(id,uploaded):[];if(editingId&&!images.length){const old=await getProperty(editingId);images=old?.images||[]}const p={id,title:$('#title').value.trim(),property_type:$('#property_type').value,price:Number($('#price').value||0),city:$('#city').value.trim(),neighborhood:$('#neighborhood').value.trim(),bedrooms:Number($('#bedrooms').value||0),suites:Number($('#suites').value||0),bathrooms:Number($('#bathrooms').value||0),parking_spaces:Number($('#parking_spaces').value||0),area_m2:Number($('#area_m2').value||0),description:$('#description').value.trim(),youtube_url:$('#youtube_url').value.trim(),images,status:$('#status').value,featured:$('#featured').checked,published:$('#published').checked,updated_at:new Date().toISOString()};if(supabaseClient){const {error}=await supabaseClient.from('properties').upsert(p);if(error)throw error}else{const list=getLocal();const ix=list.findIndex(x=>x.id===id);if(ix>=0)list[ix]=p;else list.unshift(p);saveLocal(list)}$('#save-msg').textContent='Imóvel ON no site!';$('#save-msg').className='notice success';resetForm();show('#properties-view');await renderList()}catch(err){$('#save-msg').textContent='Erro: '+err.message;$('#save-msg').className='notice'}finally{btn.disabled=false;btn.textContent='Salvar imóvel'}}
window.editProperty=async id=>{const p=await getProperty(id);if(!p)return;editingId=id;$('#form-title').textContent='Editar imóvel';for(const k of ['title','property_type','price','city','neighborhood','bedrooms','suites','bathrooms','parking_spaces','area_m2','description','youtube_url','status'])if($('#'+k))$('#'+k).value=p[k]??'';$('#featured').checked=!!p.featured;$('#published').checked=p.published!==false;$('#image-previews').innerHTML=(p.images||[]).map(x=>`<img src="${x}">`).join('');show('#form-view')};
window.deleteProperty=async id=>{if(!confirm('Excluir este imóvel?'))return;if(supabaseClient){const {error}=await supabaseClient.from('properties').delete().eq('id',id);if(error)return alert(error.message)}else saveLocal(getLocal().filter(x=>x.id!==id));await renderList()};
