const CFG=window.GIDEON_CONFIG||{};
const configured=CFG.SUPABASE_URL&&!CFG.SUPABASE_URL.includes('COLE_AQUI')&&CFG.SUPABASE_PUBLISHABLE_KEY&&!CFG.SUPABASE_PUBLISHABLE_KEY.includes('COLE_AQUI');
const supabaseClient=configured?window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY):null;
const SEEDS=[
{id:'una-areiao',title:'UNA Areião',property_type:'Lançamento',price:null,city:'Goiânia',neighborhood:'Setor Marista / Parque Areião',bedrooms:3,suites:3,bathrooms:4,parking_spaces:2,area_m2:109.75,description:'Um lançamento para morar ou investir em uma das regiões mais desejadas de Goiânia. O UNA Areião reúne arquitetura contemporânea, lazer completo, apartamentos de 66,41 m² a 109,75 m² e acesso rápido ao Parque Areião, Avenida 136, Ricardo Paranhos e região do Flamboyant. Consulte disponibilidade, tipologias e condições comerciais.',youtube_url:'',images:['assets/una/una-1.jpg','assets/una/una-2.jpg','assets/una/una-3.jpg','assets/una/una-4.jpg','assets/una/una-5.jpg'],status:'Disponível',featured:true,published:true,image_fit:'contain'},
{id:'jardins-versalhes-q15-l3',code:'GI-0001',title:'Lote no Jardins Versalhes',property_type:'Lote/Terreno',price:260000,city:'Goiânia',neighborhood:'Jardins Versalhes',bedrooms:0,suites:0,bathrooms:0,parking_spaces:0,area_m2:235.20,quadra:'15',lote:'03',description:'Excelente oportunidade para construir no Jardins Versalhes. Lote de 235,20 m², localizado na Quadra 15, Lote 03, em posição privilegiada na parte alta do condomínio. O imóvel está quitado, registrado e pronto para transferência. O condomínio oferece infraestrutura completa, segurança, áreas verdes, playground e espaços esportivos para toda a família.',youtube_url:'',images:['assets/versalhes/lote-1.jpg','assets/versalhes/lote-2.jpg','assets/versalhes/lote-3.jpg','assets/versalhes/lote-4.jpg','assets/versalhes/lote-5.jpg'],status:'Disponível',featured:true,published:true,paid_off:true,registered:true},
{id:'passos-flamboyant',code:'GI-0002',title:'Passos Flamboyant',property_type:'Lançamento',price:null,city:'Goiânia',neighborhood:'Alto da Glória / Flamboyant',bedrooms:2,suites:1,bathrooms:2,parking_spaces:1,area_m2:0,description:'Lançamento em localização estratégica, próximo ao Flamboyant Shopping e ao Alto da Glória. Projeto pensado para quem busca mobilidade, valorização e praticidade. Consulte as tipologias, metragens, valores e condições comerciais disponíveis.',youtube_url:'',images:['assets/passos/passos-1.jpg'],status:'Disponível',featured:false,published:true,image_fit:'contain'},
{id:'casamerica-parque-cascavel',code:'GI-0003',title:'Casamérica Parque Cascavel',property_type:'Lançamento',price:null,city:'Goiânia',neighborhood:'Parque Cascavel / Jardim América',bedrooms:2,suites:1,bathrooms:2,parking_spaces:1,area_m2:0,description:'Empreendimento próximo ao Parque Cascavel e a poucos minutos da Avenida T-63. Uma opção para morar ou investir em uma região com ampla estrutura de serviços, comércio e mobilidade. Consulte tipologias, metragens, disponibilidade e condições comerciais.',youtube_url:'',images:['assets/casamerica/casamerica-1.jpg'],status:'Disponível',featured:false,published:true,image_fit:'contain'},
{id:'casa-buriti-sereno-cinza',code:'GI-0004',title:'Casa no Buriti Sereno — Cinza',property_type:'Casa',price:360000,city:'Aparecida de Goiânia',neighborhood:'Buriti Sereno',bedrooms:2,suites:2,bathrooms:3,parking_spaces:2,area_m2:222,description:'Casa nova no Buriti Sereno, com duas suítes, sala integrada, cozinha com bancada em granito, lavabo, área gourmet com churrasqueira, quintal e amplo corredor lateral. Imóvel com acabamento moderno e lote de 222 m².',youtube_url:'',images:['assets/buriti-cinza/cinza-1.jpg','assets/buriti-cinza/cinza-2.jpg','assets/buriti-cinza/cinza-3.jpg','assets/buriti-cinza/cinza-4.jpg','assets/buriti-cinza/cinza-5.jpg','assets/buriti-cinza/cinza-6.jpg'],status:'Disponível',featured:true,published:true},
{id:'casa-buriti-sereno-marrom',code:'GI-0005',title:'Casa no Buriti Sereno — Marrom',property_type:'Casa',price:350000,city:'Aparecida de Goiânia',neighborhood:'Buriti Sereno',bedrooms:2,suites:2,bathrooms:3,parking_spaces:2,area_m2:189,description:'Casa nova no Buriti Sereno, com duas suítes, sala integrada, área gourmet, lavabo e quintal. Lote de 189 m², fachada contemporânea e ambientes bem distribuídos para uma rotina confortável.',youtube_url:'',images:['assets/buriti-marrom/marrom-1.jpg','assets/buriti-marrom/marrom-2.jpg','assets/buriti-marrom/marrom-3.jpg','assets/buriti-marrom/marrom-4.jpg'],status:'Disponível',featured:false,published:true},
{id:'casa-aeroporto-sul',code:'GI-0006',title:'Casa no Setor Aeroporto Sul',property_type:'Casa',price:530000,city:'Aparecida de Goiânia',neighborhood:'Setor Aeroporto Sul',bedrooms:3,suites:1,bathrooms:3,parking_spaces:4,area_m2:183,description:'Casa totalmente reformada, sozinha no lote e pronta para morar. São 183 m² construídos em lote de 360 m², com três quartos, sendo uma suíte, sala e cozinha integradas, cozinha com armários, ilha em granito Preto Via Láctea, cooktop Brastemp novo, ampla varanda, jardim, área gourmet com churrasqueira e lavabo, lavanderia e poço artesiano próprio. Garagem para quatro carros, sendo três cobertos. Imóvel avaliado em R$ 642 mil pela Caixa Econômica. Entrada facilitada.',youtube_url:'',images:['assets/aeroporto-sul/aeroporto-1.jpg','assets/aeroporto-sul/aeroporto-2.jpg','assets/aeroporto-sul/aeroporto-3.jpg','assets/aeroporto-sul/aeroporto-4.jpg','assets/aeroporto-sul/aeroporto-5.jpg','assets/aeroporto-sul/aeroporto-6.jpg'],status:'Disponível',featured:true,published:true},
{id:'residencial-caribe',code:'GI-0007',title:'Apartamento no Residencial Caribe',property_type:'Apartamento',price:360000,city:'Aparecida de Goiânia',neighborhood:'A 800 m do Buriti Shopping',bedrooms:2,suites:1,bathrooms:2,parking_spaces:2,area_m2:64,description:'Apartamento completo, moderno e pronto para morar, a aproximadamente 800 metros do Buriti Shopping. Possui dois quartos, sendo uma suíte, armários planejados, ar-condicionado no quarto principal, cortinas, cozinha equipada com cooktop, forno e sugar, além de duas vagas cobertas em formato gaveta. Valor sem mobília: R$ 360.000. Opção porteira fechada: R$ 390.000.',youtube_url:'',images:['assets/caribe/caribe-1.jpg','assets/caribe/caribe-2.jpg','assets/caribe/caribe-3.jpg','assets/caribe/caribe-4.jpg','assets/caribe/caribe-5.jpg','assets/caribe/caribe-6.jpg'],status:'Disponível',featured:true,published:true,secondary_price:'Porteira fechada: R$ 390.000'}
];
function money(v){if(v===null||v===undefined||Number(v)<=0)return 'Consulte valores';return Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}
function slug(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function wa(text){return `https://wa.me/${CFG.WHATSAPP}?text=${encodeURIComponent(text)}`}
function getLocal(){try{return JSON.parse(localStorage.getItem('gideon_properties')||'[]')}catch{return []}}
function saveLocal(v){localStorage.setItem('gideon_properties',JSON.stringify(v))}
async function getProperties(admin=false){if(supabaseClient){let q=supabaseClient.from('properties').select('*').order('featured',{ascending:false}).order('created_at',{ascending:false});if(!admin)q=q.eq('published',true);const {data,error}=await q;if(!error&&data&&data.length)return [...SEEDS,...data].filter((p,i,a)=>a.findIndex(x=>x.id===p.id)===i).filter(p=>admin||p.published!==false)}const local=getLocal();return [...SEEDS,...local].filter((p,i,a)=>a.findIndex(x=>x.id===p.id)===i).filter(p=>admin||p.published!==false)}
async function getProperty(id){const seed=SEEDS.find(x=>x.id===id);if(seed)return seed;if(supabaseClient){const {data}=await supabaseClient.from('properties').select('*').eq('id',id).maybeSingle();if(data)return data}return getLocal().find(x=>x.id===id)||null}
function propertyCard(p){const img=(p.images&&p.images[0])||'assets/una/una-1.jpg';const isLot=p.property_type==='Lote/Terreno';const featureHtml=isLot?`<span>${Number(p.area_m2||0).toLocaleString('pt-BR')} m²</span><span>Quadra ${p.quadra||'-'}</span><span>Lote ${p.lote||'-'}</span><span>${p.paid_off?'Quitado':'Disponível'}</span>`:`<span>${p.bedrooms||0} quartos</span><span>${p.suites||0} suítes</span><span>${p.parking_spaces||0} vagas</span>${Number(p.area_m2||0)>0?`<span>${Number(p.area_m2).toLocaleString('pt-BR')} m²</span>`:''}`;const fit=p.image_fit==='contain'?' contain':'';return `<article class="property-card"><a href="imovel.html?id=${encodeURIComponent(p.id)}"><div class="property-image${fit}"><img src="${img}" alt="${p.title}"><span class="tag">${p.property_type||'Imóvel'}</span></div><div class="property-body"><h3>${p.title}</h3><div class="location">${p.neighborhood||''}${p.neighborhood&&p.city?' · ':''}${p.city||''}</div><div class="features">${featureHtml}</div><div class="price">${money(p.price)}</div>${p.secondary_price?`<div class="secondary-price">${p.secondary_price}</div>`:''}</div></a></article>`}
