const CFG=window.GIDEON_CONFIG||{};
const configured=CFG.SUPABASE_URL&&!CFG.SUPABASE_URL.includes('COLE_AQUI')&&CFG.SUPABASE_PUBLISHABLE_KEY&&!CFG.SUPABASE_PUBLISHABLE_KEY.includes('COLE_AQUI');
const supabaseClient=configured?window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY):null;
const SEED={id:'una-areiao',title:'UNA Areião',property_type:'Lançamento',price:null,city:'Goiânia',neighborhood:'Setor Marista / Parque Areião',bedrooms:3,suites:3,bathrooms:4,parking_spaces:2,area_m2:109.75,description:'Um lançamento para morar ou investir em uma das regiões mais desejadas de Goiânia. O UNA Areião reúne arquitetura contemporânea, lazer completo, apartamentos de 66,41 m² a 109,75 m² e acesso rápido ao Parque Areião, Avenida 136, Ricardo Paranhos e região do Flamboyant. Consulte disponibilidade, tipologias e condições comerciais.',youtube_url:'',images:['assets/una/una-1.jpg','assets/una/una-2.jpg','assets/una/una-3.jpg','assets/una/una-4.jpg','assets/una/una-5.jpg'],status:'Disponível',featured:true,published:true};
function money(v){if(v===null||v===undefined||Number(v)<=0)return 'Consulte valores';return Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}
function slug(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function wa(text){return `https://wa.me/${CFG.WHATSAPP}?text=${encodeURIComponent(text)}`}
function getLocal(){try{return JSON.parse(localStorage.getItem('gideon_properties')||'[]')}catch{return []}}
function saveLocal(v){localStorage.setItem('gideon_properties',JSON.stringify(v))}
async function getProperties(admin=false){if(supabaseClient){let q=supabaseClient.from('properties').select('*').order('featured',{ascending:false}).order('created_at',{ascending:false});if(!admin)q=q.eq('published',true);const {data,error}=await q;if(!error&&data)return data.length?data:[SEED]}const local=getLocal();return [SEED,...local].filter((p,i,a)=>a.findIndex(x=>x.id===p.id)===i).filter(p=>admin||p.published!==false)}
async function getProperty(id){if(id==='una-areiao')return SEED;if(supabaseClient){const {data}=await supabaseClient.from('properties').select('*').eq('id',id).maybeSingle();if(data)return data}return getLocal().find(x=>x.id===id)||null}
function propertyCard(p){const img=(p.images&&p.images[0])||'assets/una/una-1.jpg';return `<article class="property-card"><a href="imovel.html?id=${encodeURIComponent(p.id)}"><div class="property-image"><img src="${img}" alt="${p.title}"><span class="tag">${p.property_type||'Imóvel'}</span></div><div class="property-body"><h3>${p.title}</h3><div class="location">${p.neighborhood||''}${p.neighborhood&&p.city?' · ':''}${p.city||''}</div><div class="features"><span>${p.bedrooms||0} quartos</span><span>${p.suites||0} suítes</span><span>${p.parking_spaces||0} vagas</span><span>${Number(p.area_m2||0).toLocaleString('pt-BR')} m²</span></div><div class="price">${money(p.price)}</div></div></a></article>`}
