window.GIDEON_CONFIG = {
  SUPABASE_URL: "COLE_AQUI_A_URL_DO_SUPABASE",
  SUPABASE_PUBLISHABLE_KEY: "COLE_AQUI_A_CHAVE_PUBLICA_DO_SUPABASE",
  WHATSAPP: "5562985358275",
  EMAIL: "contato@gideonimoveis.com.br",
  INSTAGRAM: "gideon_ta_on"
};
